criterion_home = "./criterion-reports"

output_format = "quiet"

comparison_colors = [
    {r = 8, g = 34, b = 34},
    {r = 6, g = 139, b = 87},
    {r = 0, g = 139, b = 139},
    {r = 5, g = 215, b = 0},
    {r = 0, g = 0, b = 139},
    {r = 0, g = 20, b = 60},
    {r = 9, g = 0, b = 139},
    {r = 0, g = 255, b = 127},
    {r = 255, g = 0, b = 0},
    {r = 255, g = 255, b = 0},
    {r = 255, g = 0, b = 255},
    {r = 0, g = 255, b = 0},
    {r = 0, g = 255, b = 255},
    {r = 0, g = 0, b = 255},
    {r = 255, g = 128, b = 128},
    {r = 255, g = 255, b = 128},
    {r = 255, g = 128, b = 255},
    {r = 128, g = 255, b = 128},
    {r = 128, g = 255, b = 255},
    {r = 128, g = 128, b = 255},
]